"""Rebuild the five standalone first-round design examples (not production routes)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'docs/design-round-1'
FOOTER = '''<footer class="site-footer"><span>2026 - ONPF</span><a href="/license">MIT No Attribution (MIT-0)</a><span>Self-hosted. Open source. Yours to adapt.</span></footer>'''
NAV = '''<header><a class="brand" href="index.html">ONPF<span aria-hidden="true">.</span></a><nav aria-label="Main navigation"><a href="#about">About the system</a><a href="/login">Sign in ↗</a></nav></header>'''
DESCRIPTION = 'A self-hosted workspace for designing community programs. Gather contributions, develop proposals, record owner decisions, and share reusable documents.'
BASIC = 'Runs on your own installation. No AI account or cloud service required.'
STEPS = [
    ('01', 'Listen', 'Gather contributions online, on paper, or in meetings. Keep corrections and different perspectives visible.'),
    ('02', 'Develop', 'Refine proposals, record decisions, and approve an exact document version before release.'),
    ('03', 'Share', 'Export editable ODT, Markdown and CSV files. Adapt public program packages for local use.'),
]


def flow(numbers=False):
    return '<section class="flow" id="about" aria-label="How ONPF works">' + ''.join(
        f'<article>{"<b>"+n+"</b>" if numbers else ""}<h3>{title}</h3><p>{body}</p></article>'
        for n, title, body in STEPS) + '</section>'


def save(number, name, theme, body):
    document = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{number} · {name} — ONPF design preview</title><link rel="stylesheet" href="base.css"></head><body class="{theme}"><a class="skip" href="#main">Skip to content</a><div class="preview-note">ROUND 1 / {number} — {name.upper()} · <a href="index.html">Compare all five layouts</a> · Design preview</div>{body}</body></html>'''
    (OUT / f'{number}.html').write_text(document, encoding='utf-8')


save('01', 'Common Ground', 'editorial', f'''<div class="wrap">{NAV}<main id="main"><section class="hero"><div><div class="eyebrow">Open-Source Non-Profit Project Framework</div><h1>Good ideas.<br>Shared purpose.<br><em>Real possibilities.</em></h1><p>{DESCRIPTION}</p><div class="links"><a class="button" href="/login">Enter your workspace ↗</a><a href="#about">How it works ↓</a></div></div><div class="paper"><div class="circle" aria-hidden="true">✳</div><div class="eyebrow">From conversation to program</div><ol><li><b>01</b>Listen to contributions</li><li><b>02</b>Shape the program</li><li><b>03</b>Share what works</li></ol></div></section>{flow()}<p class="small">{BASIC} Accounts are created by your installation administrator.</p></main>{FOOTER}</div>''')

save('02', 'Open / Possible', 'poster', f'''<div class="wrap">{NAV}<main id="main"><section class="hero"><div><div class="eyebrow">Open-Source Non-Profit Project Framework</div><h1>BUILD<br>WHAT<br>MATTERS.</h1><a class="button" href="/login">OPEN YOUR WORKSPACE ↗</a></div><div class="intro"><div class="symbol" aria-hidden="true"><span></span><span></span><span></span></div><div><p>{DESCRIPTION}</p><p class="small">An open framework.<br>A local installation.<br>Your community’s ideas.</p></div></div></section>{flow(True)}<p class="small" style="margin-top:22px">{BASIC} Use an administrator-created account to sign in.</p></main>{FOOTER}</div>''')

save('03', 'Civic Blueprint', 'blueprint', f'''<div class="wrap">{NAV}<main id="main"><section class="hero"><div><div class="eyebrow">Open-Source Non-Profit Project Framework</div><h1>A clear path from<br><span>community input</span><br>to shared programs.</h1><p>{DESCRIPTION}</p><div class="links"><a class="button" href="/login">Access workspace →</a><a href="#about">Explore the workflow</a></div><p class="small" style="margin-top:23px">{BASIC}</p></div><div class="diagram" aria-label="Workflow: contributions, proposals and decisions, reusable release"><div class="eyebrow" style="margin-bottom:22px">PROGRAM DESIGN / WORKFLOW</div><div class="node">01 / CONTRIBUTIONS<small>Online · Paper · Meetings</small></div><div class="connector"></div><div class="node">02 / PROPOSALS + DECISIONS<small>Manual refinement · Exact-version approval</small></div><div class="connector"></div><div class="node">03 / REUSABLE RELEASE<small>Editable documents · Local adaptation</small></div></div></section>{flow()}<p class="small">Your installation manages its own accounts and data. Ask its administrator for access.</p></main>{FOOTER}</div>''')

save('04', 'Idea Mosaic', 'mosaic', f'''<div class="wrap">{NAV}<main id="main"><section class="hero"><div class="eyebrow">Open-Source Non-Profit Project Framework</div><h1>Small ideas.<br>Room to grow.</h1><p>{DESCRIPTION}</p><a class="button" href="/login">Step into your workspace ↗</a></section><section class="tiles" id="about" aria-label="About ONPF"><article class="tile first"><div><div class="eyebrow">01 / Bring ideas together</div><div class="orb" aria-hidden="true"></div></div><div><h2>Every perspective<br>has a place.</h2><p>Collect input online, on paper, or in meetings. Preserve contributions and their corrections.</p></div></article><article class="tile second"><div class="eyebrow">02 / Shape a program</div><h2>Turn the conversation into a plan.</h2><p>Refine proposals, record owner decisions, and approve the exact version you want to release.</p></article><article class="tile"><div class="eyebrow">03 / Make it reusable</div><h2>Share.<br>Adapt. Repeat.</h2><p>Editable ODT, Markdown and CSV exports, plus public packages for local adaptation.</p></article><article class="tile last"><div class="eyebrow">Your installation</div><h2>A workspace<br>you run.</h2><p>No AI account or cloud service required. Your administrator creates accounts and manages access.</p></article></section></main>{FOOTER}</div>''')

save('05', 'Field Guide', 'index', f'''<div class="shell"><aside><a class="brand" href="index.html">ONPF<span aria-hidden="true">/</span></a><p>Open-Source Non-Profit<br>Project Framework</p><nav aria-label="Main navigation"><a href="#main">01 &nbsp; Overview</a><a href="#about">02 &nbsp; How it works</a><a href="/license">03 &nbsp; License</a></nav><div class="aside-bottom"><p>Designed for local use.<br>Open to adaptation.</p><a href="/login">Sign in →</a></div></aside><div class="wrap"><main id="main"><div class="eyebrow">A practical framework for community programs</div><h1>Give your next<br>program a<br>clear starting point.</h1><p class="lead">{DESCRIPTION}</p><div class="links"><a class="button" href="/login">Enter workspace →</a><span class="small">Administrator-created account required</span></div><section class="steps" id="about" aria-label="How it works">{''.join(f'<article class="step"><span>{n}</span><h2>{title}</h2><p>{body}</p></article>' for n,title,body in STEPS)}</section><p class="small" style="margin-top:25px">{BASIC} Each installation manages its own accounts and data.</p></main>{FOOTER}</div></div>''')

choices = [('01', 'Common Ground', 'Warm ivory, serif headlines, an organic process illustration.', '#e6e8da'), ('02', 'Open / Possible', 'Electric yellow, oversized type, bold geometric forms.', '#f4f349'), ('03', 'Civic Blueprint', 'Dark navy, mint accents, a diagram-led technical feel.', '#101d2a'), ('04', 'Idea Mosaic', 'Pastel tiles, rounded shapes, a playful modular layout.', '#e2d9f6'), ('05', 'Field Guide', 'Quiet sidebar, cobalt accents, a structured reading flow.', '#eef1f6')]
cards = ''.join(f'''<article><div class="thumb"><iframe src="{n}.html" title="{name} preview" tabindex="-1" loading="lazy"></iframe><a class="cover" href="{n}.html" aria-label="Open {name}"></a></div><div class="caption"><span>{n}</span><div><h2><a href="{n}.html">{name} ↗</a></h2><p>{desc}</p></div></div></article>''' for n,name,desc,color in choices)
(OUT / 'index.html').write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ONPF · Five directions / Round 1</title><style>*{{box-sizing:border-box}}body{{margin:0;background:#e9edf1;color:#202a38;font:15px/1.5 Arial,sans-serif}}main{{max-width:1460px;padding:40px;margin:auto}}header{{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:32px}}h1{{font-size:38px;line-height:1.1;letter-spacing:-1.3px;margin:8px 0}}header p{{max-width:530px;margin:8px 0 0}}small{{text-transform:uppercase;letter-spacing:2px}}.grid{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:28px}}article{{background:white;border:1px solid #ccd4dd;border-radius:12px;overflow:hidden}}.thumb{{aspect-ratio:1200/1000;overflow:hidden;position:relative;background:white}}iframe{{position:absolute;top:0;left:0;width:1200px;height:1000px;border:0;transform-origin:top left;pointer-events:none}}.cover{{position:absolute;inset:0}}.cover:focus-visible{{outline:5px solid #234cd5;outline-offset:-5px}}.caption{{display:flex;gap:16px;padding:22px;border-top:1px solid #ddd}}.caption>span{{font:22px Georgia;color:#77879a}}h2{{font-size:21px;margin:0}}a{{color:inherit;text-decoration:none}}a:hover{{text-decoration:underline}}.caption p{{margin:5px 0 0;color:#556474;font-size:13px}}.note{{background:#dce4ef;border-radius:12px;padding:32px;display:flex;flex-direction:column;justify-content:center}}.note h2{{font-size:30px}}.note p{{max-width:40ch}}@media(max-width:760px){{main{{padding:20px}}header{{display:block}}h1{{font-size:30px}}.grid{{grid-template-columns:1fr}}}}</style></head><body><main><header><div><small>ONPF / Design exploration / Round 1</small><h1>One framework. Five directions.</h1><p>Choose a starting point for refinement. Open any preview to explore its full layout and working license link.</p></div><p>Same system. Different visual approaches.<br>No people imagery. No layout selected yet.</p></header><div class="grid">{cards}<section class="note"><small>Your next decision</small><h2>What feels right<br>for ONPF?</h2><p>Choose one direction, or combine specific elements from several. The headline, colours, spacing and detail can all be refined next.</p><p>Every concept includes system information, sign-in access, and the <a href="/license" style="text-decoration:underline">MIT No Attribution license</a>.</p></section></div></main><script>const observer=new ResizeObserver(entries=>{{for(const entry of entries){{entry.target.querySelector('iframe').style.transform='scale('+entry.contentRect.width/1200+')';}}}});document.querySelectorAll('.thumb').forEach(el=>observer.observe(el));</script></body></html>''',encoding='utf-8')
print('Wrote five layout concepts and comparison gallery to', OUT)
